spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

